"""Add user preferences table

Revision ID: 0486242dd6fc
Revises: aca543ae6561
Create Date: 2026-08-08 17:03:10.854535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0486242dd6fc'
down_revision: Union[str, Sequence[str], None] = 'aca543ae6561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferred_voice', sa.String(length=100), nullable=False),
    sa.Column('speech_speed', sa.Float(), nullable=False),
    sa.Column('font_size', sa.Integer(), nullable=False),
    sa.Column('dyslexia_mode', sa.Boolean(), nullable=False),
    sa.Column('high_contrast_mode', sa.Boolean(), nullable=False),
    sa.Column('preferred_language', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
